logging:
  level:
    org.springframework: info
spring:
  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
extendz:
  model-meta-endpoint: ${spring.data.rest.base-path}/models
  local-data-dir: data